version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001" 
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"  
    environment:
      NODE_ENV: production
